version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
